[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.6.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "2.2.0"

[prune]
  go-tests = true
  unused-packages = true
